builds:
  - binary: tmsh
    main: ./cmd/tmsh/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/shiftky/go-tmsh/cmd/tmsh/cmd.version={{.Version}}"