[[constraint]]
  branch = "master"
  name = "github.com/shiftky/go-tmsh"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"
